In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
### Vocabulary size
voc_size=10000

In [5]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4643, 3121, 1658, 3385], [4643, 3121, 1658, 6250], [4643, 8509, 1658, 6657], [6321, 1704, 1246, 8363, 556], [6321, 1704, 1246, 8363, 6499], [2309, 4643, 4868, 1658, 2180], [9307, 5642, 5804, 8363]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4643 3121 1658 3385]
 [   0    0    0    0 4643 3121 1658 6250]
 [   0    0    0    0 4643 8509 1658 6657]
 [   0    0    0 6321 1704 1246 8363  556]
 [   0    0    0 6321 1704 1246 8363 6499]
 [   0    0    0 2309 4643 4868 1658 2180]
 [   0    0    0    0 9307 5642 5804 8363]]


In [9]:
dim=10


In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[ 0.02763386 -0.03063743  0.02073287 -0.01915964  0.01524409
    0.02584149  0.03144649 -0.03123146 -0.04502023 -0.04061969]
  [ 0.02763386 -0.03063743  0.02073287 -0.01915964  0.01524409
    0.02584149  0.03144649 -0.03123146 -0.04502023 -0.04061969]
  [ 0.02763386 -0.03063743  0.02073287 -0.01915964  0.01524409
    0.02584149  0.03144649 -0.03123146 -0.04502023 -0.04061969]
  [ 0.02763386 -0.03063743  0.02073287 -0.01915964  0.01524409
    0.02584149  0.03144649 -0.03123146 -0.04502023 -0.04061969]
  [-0.03049705  0.00591396  0.01050172 -0.00447292 -0.02596564
    0.01777581  0.04855521  0.02329976  0.01382856  0.04479711]
  [ 0.02416796 -0.04202925 -0.03707222  0.00125026 -0.03853554
    0.01763606 -0.00784434  0.04653332 -0.02930667  0.03154138]
  [-0.02228685  0.04889052 -0.02624414  0.00809271  0.0385205
    0.01332015  0.03088809  0.00317141  0.0428247   0.03571465]
  [-0.0263669  -0.02786206  0.0160333  -0.00470922  0.04269609
   -0.04541569  0.00342655 -0.01887237  0.0193307

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 4643, 3121, 1658, 3385])

In [14]:
print(model.predict(embedded_docs)[0])

[[ 0.02763386 -0.03063743  0.02073287 -0.01915964  0.01524409  0.02584149
   0.03144649 -0.03123146 -0.04502023 -0.04061969]
 [ 0.02763386 -0.03063743  0.02073287 -0.01915964  0.01524409  0.02584149
   0.03144649 -0.03123146 -0.04502023 -0.04061969]
 [ 0.02763386 -0.03063743  0.02073287 -0.01915964  0.01524409  0.02584149
   0.03144649 -0.03123146 -0.04502023 -0.04061969]
 [ 0.02763386 -0.03063743  0.02073287 -0.01915964  0.01524409  0.02584149
   0.03144649 -0.03123146 -0.04502023 -0.04061969]
 [-0.03049705  0.00591396  0.01050172 -0.00447292 -0.02596564  0.01777581
   0.04855521  0.02329976  0.01382856  0.04479711]
 [ 0.02416796 -0.04202925 -0.03707222  0.00125026 -0.03853554  0.01763606
  -0.00784434  0.04653332 -0.02930667  0.03154138]
 [-0.02228685  0.04889052 -0.02624414  0.00809271  0.0385205   0.01332015
   0.03088809  0.00317141  0.0428247   0.03571465]
 [-0.0263669  -0.02786206  0.0160333  -0.00470922  0.04269609 -0.04541569
   0.00342655 -0.01887237  0.01933071  0.039177  ]]